shallow_clone: true

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - packages

# Do not build on tags (GitHub only)
skip_tags: true

configuration: Release

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  sign_tool: 'C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe'
  artifact_path: 'C:\projects\Integritul\Tulpep.Integritul\bin\Release\Integritul.exe'
  timestamp_url: http://timestamp.verisign.com/scripts/timstamp.dll
  pfx_file: 'C:\projects\Integritul\tulpep.pfx'
  pfx_password:
    secure: LdcyoQhXm2P2QuFz/ogRYpACnJeZDyka/QBzMKJkKKE=


after_build:
  - cmd: '"%sign_tool%" sign /f "%pfx_file%" /p %pfx_password% /t %timestamp_url% "%artifact_path%"'

artifacts:
  - path: '**\bin\Release\Integritul.exe'
    name: Integritul.exe

deploy:
  release: Integritul-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: Q+20Xaui8ng5gVvoMIkb0g4F0oqMZFVOJo4SNRc+KVN91WkjLe5gTMkifCyDZTlE
  artifact: Integritul.exe
  draft: false
  prerelease: false
  on:
    branch: master
